config/routes.rb
Rails.application.routes.draw do

  # 顧客用


  # 顧客用
  scope module: :public do
    root to: 'homes#top'
    get 'homes/about'
    # Customers
    get 'customers' => 'customers#show'
    get 'customers/edit' => 'customers#edit'
    patch 'customers' => 'customers#update'
    get 'customers/confirm_withdraw' => 'customers#confirm_withdraw'
    patch 'customers/withdraw' => 'customers#withdraw'
    # CartItems
    delete 'cart_items/destroy_all' => 'cart_items#destroy_all'
    # Orders
    post 'orders/confirm' => 'orders#confirm'
    get 'orders/thanks' => 'orders#thanks'
    resources :orders, only:[:new, :index, :show, :create]
    resources :items, only:[:index, :show]
    resources :cart_items, only:[:index, :show, :create, :update, :destroy]

    devise_for :customers,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  end

  # 管理者用
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
  }

  # 管理者用
  namespace :admin do
    root to: 'homes#top'
    get 'homes/about'
    resources :orders, only:[:index, :show]
    resources :items
    resources :customers, only:[:index, :show, :edit, :update]

  end


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/item.rb
class Item < ApplicationRecord
  has_one_attached :image
  has_many :cart_items, dependent: :destroy
  has_many :order_details, dependent: :destroy

  def with_tax_price
    (price * 1.1).floor
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to admin_item_path(@item)
    else
      render :new
    end
  end

  def index
    @items = Item.page(params[:page])
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    if @item.update(item_params)
    redirect_to admin_item_path(@item.id)
    else
    render :edit
    end
  end

  def destroy
    item = Item.find(params[:id])
    item.destroy
    redirect_to admin_items_path
  end

  private
  def item_params
    params.require(:item).permit(:name, :introduction, :price, :image)
  end

end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/views/admin/items/edit.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
    <h1>商品編集</h1>

    <%= form_with url: admin_item_path(@item.id), model: @item do |f| %>
      <div class="form-group">
      <label for="inputImage">商品画像</label>
      <%= f.file_field :image  %>
      </div>
      <div class="form-group">
      <label for="inputName">商品名</label>
      <%= f.text_field :name, autofocus: true, placeholder:"商品名",　class:"form-control book_title" %>
      </div>
      <div class="form-group">
      <label for="inputIntroduction">商品説明</label>
      <%= f.text_field :introduction, placeholder:"商品説明",　class:"form-control book_body" %>
      </div>
      <div class="form-group">
      <label for="inputPrice">税込価格</label>
      <%= f.text_field :price, placeholder:"税込価格", class:"form-control book_body" %>
      </div>
      <div class="form-group">
      <%= f.submit "編集する", class:"btn btn-success" %>
      </div>
    <% end %>
    </div>
  </div>
</div>

app/views/admin/items/index.html.erb
<main>
  <div class="container px-5 px-sm-0">
    <div class="row">
      <div class="col-md-8 offset-md-1">
        <h2>商品一覧</h2>
        <table class="table">
          <thead>
            <tr>
            <th></th>
            <th>商品ID</th>
            <th>商品名</th>
            <th>税抜価格</th>
            <th colspan="3"></th>
            </tr>
          </thead>
          <tbody>
            <% @items.each do |item| %>
            <tr>
            <td></td>
            <td><%= item.id %></td>
            <td>
              <%= link_to admin_item_path(item.id) do %>
              <%= item.name %>
              <% end %>
            </td>
            <td><%= item.price %></td>
            </tr>
            <% end %>
        </tbody>
        </table>

        <%= link_to new_admin_item_path do %>
        新規登録
        <% end %>

        <%= paginate @items %>
      </div>
    </div>
  </div>


</main>

app/views/admin/items/new.html.erb
 <h2 class="mt-3">新規商品登録</h2>

      <%= form_with url: admin_items_path, model: @item do |f| %>
      <div class="form-group">
      <h4>商品画像</h4>
      <%= f.file_field :image, accept: "image/*" %>
      </div>
      <div class="form-group">
      <h4>商品名</h4>
      <%= f.text_field :name %>
      </div>
      <div class="form-group">
      <h4>商品説明</h4>
      <%= f.text_area :introduction %>
      </div>
      <div class="form-group">
      <h4>価格</h4>
      <%= f.text_area :price %>
      </div>
      <div class="form-group">
      <%= f.submit "新規登録", class:"btn btn-success" %>
      <% end %>
  </div>

app/views/admin/items/show.html.erb
  <div class="col-md-8 offset-md-1">
    <h2>商品詳細</h2>
    <table class="table">
    <tbody>
      <tr>
        <td>
        <% if @item.image.attached? %>
        <%= image_tag @item.image, size: "100x100" %>
        <% else %>
        <%= image_tag 'noimage', size: "100x100" %>
        <% end %>
        </td>
        <td><%= @item.name %></td>
        <td><%= @item.introduction %></td>
        <td><%= @item.price %></td>
      </tr>
    </tbody>
    </table>

    <p><%= link_to "編集する", edit_admin_item_path(@item.id), class:"btn btn-sm btn-success" %></p>
    <p><%= link_to  "削除する", admin_item_path, method: :delete, "data-confirm" => "本当に削除しますか？", class:"btn btn-sm btn-danger" %></p>
  </div>