config/routes.rb
Rails.application.routes.draw do

  # 顧客用


  # 顧客用
  scope module: :public do
    root to: 'homes#top'
    get 'homes/about'
    # Customers
    get 'customers' => 'customers#show'
    get 'customers/edit' => 'customers#edit'
    patch 'customers' => 'customers#update'
    get 'customers/confirm_withdraw' => 'customers#confirm_withdraw'
    patch 'customers/withdraw' => 'customers#withdraw'
    # CartItems
    delete 'cart_items/destroy_all' => 'cart_items#destroy_all'
    # Orders
    post 'orders/confirm' => 'orders#confirm'
    get 'orders/thanks' => 'orders#thanks'
    resources :orders, only:[:new, :index, :show, :create]
    resources :items, only:[:index, :show]
    resources :cart_items, only:[:index, :show, :create, :update, :destroy]

    devise_for :customers,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  end

  # 管理者用
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
  }

  # 管理者用
  namespace :admin do
    root to: 'homes#top'
    get 'homes/about'
    resources :orders, only:[:index, :show]
    resources :items
    resources :customers, only:[:index, :show, :edit, :update]

  end


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :cart_items, dependent: :destroy
  has_many :orders, dependent: :destroy
end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  def index
    @customers = Customer.page(params[:page])
  end

  def show
    @customer = Customer.find(params[:id])
    @order = Order.all
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    @customer = Customer.find(params[:id])
    if @customer.update(customer_params)
      redirect_to admin_customer_path(@customer.id)
    else
    render :edit
    end
  end

  private
  def customer_params
    params.require(:customer).permit(:last_name, :first_name, :postal_code, :address, :telephone_number, :email, :is_deleted)
  end

end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/views/admin/customers/edit.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
    <h2>
    <%= @customer.last_name %> <%= @customer.first_name %>
    さんの会員情報編集
    </h2>
    会員ID <%= @customer.id %><br>
    <%= form_with url: admin_customer_path(@customer.id), model: @customer do |f| %>
      <div class="form-group">
      <label>氏名</label>
      <%= f.text_field :last_name, autofocus: true %>
      <%= f.text_field :first_name, autofocus: true %>
      </div>

      <div class="form-group">
      <label>フリガナ</label>
      <%= f.text_field :last_name_kana, autofocus: true %>
      <%= f.text_field :first_name_kana %>
      </div>

      <div class="form-group">
      <label>郵便番号</label>
      <%= f.text_field :postal_code %>
      </div>

      <div class="form-group">
      <label>住所</label>
      <%= f.text_field :address %>
      </div>

      <div class="form-group">
      <label>電話番号</label>
      <%= f.text_field :telephone_number %>
      </div>

      <div class="form-group">
      <label>メールアドレス</label>
      <%= f.text_field :email %>
      </div>

      <div class="form-group">
      <label>会員ステータス</label>
      <%= f.radio_button :is_deleted, "false" %>
      <%= f.label :is_deleted_valid, "有効" %>
      <%= f.radio_button :is_deleted,  "true" %>
      <%= f.label :is_deleted_invalid, "退会" %>
      </div>
      <%= f.submit "編集する", class:"btn btn-success" %>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/customers/index.html.erb
<h2>Users</h2>
<table class="table">
  <thead>
    <tr>
    <th>会員ID</th>
    <th>氏名</th>
    <th>メールアドレス</th>
    <th>ステータス</th>
    <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
  <tr>
    <% @customers.each do |customer| %>
    <td><%= customer.id %></td>
    <td><%= link_to admin_customer_path(customer.id) do %>
      <%= customer.last_name %> <%= customer.first_name %>
      <% end %>
    </td>
    <td><%= customer.email %></td>
    <td><%= customer.is_deleted %></td>
  </tr>
  <% end %>
  </tbody>
</table>

app/views/admin/customers/show.html.erb
  <h2>
    <%= @customer.last_name %> <%= @customer.first_name %>
    さんの会員詳細
  </h2>
  <div>
      会員ID <%= @customer.id %><br>
      氏名 <%= @customer.last_name %> <%= @customer.first_name %><br>
      フリガナ <%= @customer.last_name_kana %> <%= @customer.first_name_kana %><br>
      郵便番号 <%= @customer.postal_code %><br>
      電話番号 <%= @customer.telephone_number %><br>
      メールアドレス <%= @customer.email %><br>
      会員ステータス <%= @customer.is_deleted %><br>
  </div>
  <div>
    <%= link_to edit_admin_customer_path(@customer.id), class:"btn btn-outline-secondary" do %>
    編集する
    <% end %>
  </div>
  <div>
      <%= link_to admin_orders_path(@customer), class:"btn btn-outline-secondary" do %>
    注文履歴一覧を見る
    <% end %>
  </div>

app/views/admin/customers/update.html.erb
<h1>Admin::Customers#update</h1>
<p>Find me in app/views/admin/customers/update.html.erb</p>