config/routes.rb
Rails.application.routes.draw do

  # 顧客用


  # 顧客用
  scope module: :public do
    root to: 'homes#top'
    get 'homes/about'
    # Customers
    get 'customers' => 'customers#show'
    get 'customers/edit' => 'customers#edit'
    patch 'customers' => 'customers#update'
    get 'customers/confirm_withdraw' => 'customers#confirm_withdraw'
    patch 'customers/withdraw' => 'customers#withdraw'
    # CartItems
    delete 'cart_items/destroy_all' => 'cart_items#destroy_all'
    # Orders
    post 'orders/confirm' => 'orders#confirm'
    get 'orders/thanks' => 'orders#thanks'
    resources :orders, only:[:new, :index, :show, :create]
    resources :items, only:[:index, :show]
    resources :cart_items, only:[:index, :show, :create, :update, :destroy]

    devise_for :customers,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  end

  # 管理者用
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
  }

  # 管理者用
  namespace :admin do
    root to: 'homes#top'
    get 'homes/about'
    resources :orders, only:[:index, :show]
    resources :items
    resources :customers, only:[:index, :show, :edit, :update]

  end


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/order.rb
class Order < ApplicationRecord
    belongs_to :customer
    has_many :order_details, dependent: :destroy

    enum payment_method: { credit_card: 0, transfer: 1 }
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  def show
    @order = Order.find(params[:id])
    @subtotal = 0
    @total = 0
  end

  def index
    @customer = Customer.find(params[:id])
    @order = Order.all
  end
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/views/admin/orders/index.html.erb
<h2>注文履歴一覧</h2>
<table>
  <thead>
    <tr>
      <th>注文日</th>
      <th>配送先</th>
      <th>注文商品</th>
      <th>支払金額</th>
      <th>注文詳細</th>
    </tr>
  </thead>

  <tbody>


    <% @customer.orders.each do |order| %>
    <tr>
      <!--１．注文日-->
      <th>
        <%= link_to root_path do %>
        <%= order.created_at.strftime("%Y/%m/%d %H:%M:%S") %>
        <% end %>
      </th>
      <!--２．配送先-->
      <th>
        <%= order.customer.address %>
      </th>
      <!--３．注文商品-->
      <th>
      <% order.order_details.each do |detail| %>
      <%= detail.item.name %><br>
      <% end %>
      <br>
      </th>
      <!--４．支払金額-->
      <th>
        <%= order.total_amount %>
      </th>
      <!--５．注文詳細-->
      <th>
      <%= link_to order_path(order),class:"btn btn-primary" do %>
      表示する
      <% end %>
      </th>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/admin/orders/show.html.erb
<h2>注文履歴詳細</h2>
  <h3>購入者</h3>
  <%= @order.customer.last_name + @order.customer.first_name %>

  <h3>注文日</h3>
  <%= @order.created_at.strftime("%Y/%m/%d %H:%M:%S") %>

  <h3>配送先</h3>
  〒<%= @order.postal_code %>
  <%= @order.address %><br>
  <%= @order.name %>

  <h3>支払方法</h3>
  <div class="payment_method">
    <%= @order.payment_method_i18n %>
  </div>


  <table class="table">
  <thead>
    <tr>
    <th>商品名</th>
    <th>単価（税込み）</th>
    <th>数量</th>
    <th>小計</th>
    </tr>
  </thead>
  <tbody>
    <% @order.order_details.each do |detail| %>
      <tr>
      <td><%= detail.item.name %></td>
      <td><%= detail.item.with_tax_price %></td>
      <td><%= detail.amount %></td>
      <% @subtotal = detail.item.with_tax_price * detail.amount %>
      <td><%= @subtotal %></td>
      <% @total += @subtotal %>
      </tr>
    <% end %>
      </tbody>
  </table>

  <div>
      <b>送料</b>800円<br>
      <b>商品合計</b><%= @total %><br>
      <b>請求金額合計</b><%= @total + 800 %><br>
  </div>