config/routes.rb
Rails.application.routes.draw do

  # 顧客用


  # 顧客用
  scope module: :public do
    root to: 'homes#top'
    get 'homes/about'
    # Customers
    get 'customers' => 'customers#show'
    get 'customers/edit' => 'customers#edit'
    patch 'customers' => 'customers#update'
    get 'customers/confirm_withdraw' => 'customers#confirm_withdraw'
    patch 'customers/withdraw' => 'customers#withdraw'
    # CartItems
    delete 'cart_items/destroy_all' => 'cart_items#destroy_all'
    # Orders
    post 'orders/confirm' => 'orders#confirm'
    get 'orders/thanks' => 'orders#thanks'
    resources :orders, only:[:new, :index, :show, :create]
    resources :items, only:[:index, :show]
    resources :cart_items, only:[:index, :show, :create, :update, :destroy]

    devise_for :customers,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  end

  # 管理者用
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
  }

  # 管理者用
  namespace :admin do
    root to: 'homes#top'
    get 'homes/about'
    resources :orders, only:[:index, :show]
    resources :items
    resources :customers, only:[:index, :show, :edit, :update]

  end


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :item
  belongs_to :customer

  def subtotal
    item.with_tax_price * amount
  end

end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :cart_items, dependent: :destroy
  has_many :orders, dependent: :destroy
end

app/models/item.rb
class Item < ApplicationRecord
  has_one_attached :image
  has_many :cart_items, dependent: :destroy
  has_many :order_details, dependent: :destroy

  def with_tax_price
    (price * 1.1).floor
  end
end

app/models/order.rb
class Order < ApplicationRecord
    belongs_to :customer
    has_many :order_details, dependent: :destroy

    enum payment_method: { credit_card: 0, transfer: 1 }
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
    belongs_to :item
    belongs_to :order
end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  def index
    @customers = Customer.page(params[:page])
  end

  def show
    @customer = Customer.find(params[:id])
    @order = Order.all
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    @customer = Customer.find(params[:id])
    if @customer.update(customer_params)
      redirect_to admin_customer_path(@customer.id)
    else
    render :edit
    end
  end

  private
  def customer_params
    params.require(:customer).permit(:last_name, :first_name, :postal_code, :address, :telephone_number, :email, :is_deleted)
  end

end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
    @orders = Order.all
  end

  def about
  end
  
  def show
    
  end
  
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to admin_item_path(@item)
    else
      render :new
    end
  end

  def index
    @items = Item.page(params[:page])
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    if @item.update(item_params)
    redirect_to admin_item_path(@item.id)
    else
    render :edit
    end
  end

  def destroy
    item = Item.find(params[:id])
    item.destroy
    redirect_to admin_items_path
  end

  private
  def item_params
    params.require(:item).permit(:name, :introduction, :price, :image)
  end

end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  def show
    @order = Order.find(params[:id])
    @subtotal = 0
    @total = 0
  end

  def index
    @customer = Customer.find(params[:id])
    @order = Order.all
  end
end

app/controllers/admin/passwords_controller.rb
# frozen_string_literal: true

class Admin::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/admin/sessions_controller.rb
# frozen_string_literal: true

class Admin::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]
  def after_sign_out_path_for(resource)
    new_admin_session_path # ログアウト後に遷移するpathを設定
  end
  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/admin/unlocks_controller.rb
# frozen_string_literal: true

class Admin::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?



  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NaganoCake</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <nav class="navbar navbar-expand-lg navbar-white">
        <div class="container">
        <%= link_to "LOGO", root_path, class:"nav navbar-brand p-1 btn btn-light" %>
        <ul class="nav ml-auto">
          <!--管理者用ヘッダ-->
          <% if admin_signed_in? %>
            <li class="nav-item">
            <%= link_to "商品一覧", admin_items_path, class:"nav justify-content-end btn btn-light" %></li>
            <li class="nav-item">
            <%= link_to "会員一覧", admin_customers_path, class:"nav justify-content-end btn btn-light" %></li>
            <li class="nav-item">
            <%= link_to "注文履歴一覧", admin_root_path, class:"nav justify-content-end btn btn-light" %></li>
            <li class="nav-item">
            <%= link_to "ログアウト", destroy_admin_session_path, method: :delete, class:"nav justify-content-end btn btn-light" %></li>

          <!--顧客用ヘッダ-->
          <% elsif customer_signed_in? %>
            <li class="nav-item btn btn-light">
            <%= link_to "マイページ", customers_path, class:"nav justify-content-end btn btn-light" %></li>
            <li class="nav-item btn btn-light">
            <%= link_to "商品一覧", items_path, class:"nav justify-content-end btn btn-light" %></li>
            <li class="nav-item btn btn-light">
            <%= link_to "カート", cart_items_path, class:"nav justify-content-end btn btn-light" %></li>
            <li class="nav-item btn btn-light">
            <%= link_to "ログアウト", destroy_customer_session_path, method: :delete, class:"nav justify-content-end btn btn-light" %></li>

          <!--ログイン前-->
          <% else %>
            <li class="nav-item btn btn-light">
            <%= link_to "About", homes_about_path %></li>
            <li class="nav-item btn btn-light">
            <%= link_to "商品一覧", items_path %></li>
            <li class="nav-item btn btn-light">
            <%= link_to "新規登録", new_customer_registration_path %></li>
            <li class="nav-item btn btn-light">
            <%= link_to "ログイン", new_customer_session_path %></li>
          <% end %>
        </ul>
        </div>
      </nav>
    </header>
    <%= yield %>
  </body>
</html>